version: 2.1

parameters:
  node-version:
    type: string
    default: '16.17.0'

jobs:
  build:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - save_cache:
          key: yarn-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - '.yarn/cache'

      - run: yarn npm audit --recursive --severity=critical
      - run: yarn dedupe --check
      - run: yarn pretty:check

      - run: NODE_ENV=test yarn test --coverage --coverageReporters=json --reporters=jest-junit --runInBand

      - store_test_results:
          path: './junit.xml'

      - run: |-
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN} --file ./coverage/coverage-final.json
